# プレフィックスを Ctrl+a に変更（好みで）
# unbind C-b
# set -g prefix C-a

# マウス有効化
set -g mouse on

# 256色
set -g default-terminal "screen-256color"

# ペイン分割を | と - で
bind | split-window -h
bind - split-window -v

# ステータスバーの色
set -g status-bg black
set -g status-fg white
